import { GoogleGenAI, Modality, Type } from "@google/genai";
import { useStore } from '../hooks/useStore';

let ai: GoogleGenAI | null = null;
let userProvidedKey: string | null = null;

// This will be called by the store to set a user-entered key
export const setUserProvidedApiKey = (key: string | null) => {
    userProvidedKey = key;
    ai = null; // Force re-initialization on next call
};

// This is the singleton getter
const getGenAIClient = (): GoogleGenAI | null => {
    if (ai) {
        return ai;
    }
    
    const key = userProvidedKey || process.env.API_KEY;

    if (key) {
        try {
            ai = new GoogleGenAI({ apiKey: key });
            return ai;
        } catch (e) {
            console.error("Failed to initialize GoogleGenAI:", e);
            ai = null; // Ensure ai is null on failure
            return null;
        }
    }
    
    return null;
};

export const verifyApiKey = async (key: string): Promise<boolean> => {
    try {
        const testClient = new GoogleGenAI({ apiKey: key });
        // Perform a lightweight, low-cost operation to confirm validity.
        await testClient.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: 'test',
            config: {
                maxOutputTokens: 1,
            },
        });
        return true;
    } catch (error) {
        console.error("API Key validation failed:", error);
        return false;
    }
};


export async function* generateTextStream(prompt: string): AsyncGenerator<string> {
    const client = getGenAIClient();
    if (!client) throw new Error("Gemini client not initialized. API Key may be missing or invalid.");

    const state = useStore.getState();
    const modelName = state.settings.engine.cloud.textModel;
    
    const activePersona = state.settings.engine.cloud.personas.find(p => p.id === state.settings.engine.cloud.activePersonaId);
    const systemInstruction = activePersona ? activePersona.prompt : "You are a helpful AI assistant.";

    try {
        const response = await client.models.generateContentStream({
            model: modelName,
            contents: prompt,
            config: {
                systemInstruction,
            },
        });

        for await (const chunk of response) {
            yield chunk.text;
        }
    } catch (error) {
        console.error("Gemini streaming text generation error:", error);
        throw new Error("Failed to generate streaming text from Gemini API.");
    }
}

export async function generateEnhancedPrompt(prompt: string): Promise<string> {
    const client = getGenAIClient();
    if (!client) throw new Error("Gemini client not initialized. API Key may be missing or invalid.");

    const modelName = useStore.getState().settings.engine.cloud.textModel;
    const fullPrompt = `Rephrase the following first-person player action into a descriptive, third-person literary action. Only return the rephrased action, no other text.\n\nORIGINAL: "${prompt}"\n\nREPHRASED:`;
     try {
        const response = await client.models.generateContent({
            model: modelName,
            contents: fullPrompt,
        });
        return response.text.trim();
    } catch (error) {
        console.error("Gemini prompt enhancement error:", error);
        throw new Error("Failed to generate enhanced prompt from Gemini API.");
    }
}

export const generateImage = async (prompt: string, modelNameOverride?: string): Promise<string> => {
  const client = getGenAIClient();
  if (!client) throw new Error("Gemini client not initialized. API Key may be missing or invalid.");
    
  const modelName = modelNameOverride || useStore.getState().settings.engine.cloud.imageModel;
  
  try {
    const response = await client.models.generateImages({
        model: modelName,
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: '1:1',
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
        return response.generatedImages[0].image.imageBytes;
    } else {
        throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Gemini image generation error:", error);
    throw new Error("Failed to generate image from Gemini API.");
  }
};


export const suggestActionFromContext = async (context: string): Promise<string[]> => {
    const client = getGenAIClient();
    if (!client) throw new Error("Gemini client not initialized. API Key may be missing or invalid.");

    const modelName = useStore.getState().settings.engine.cloud.textModel;
    const prompt = `Given the following game context, suggest 1-3 creative and relevant actions or lines of dialogue for the player character. The suggestions should be in the character's voice.\n\nCONTEXT:\n${context}\n\nSUGGESTIONS:`;

    try {
        const response = await client.models.generateContent({
            model: modelName,
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        suggestions: {
                            type: Type.ARRAY,
                            items: { type: Type.STRING }
                        }
                    }
                }
            }
        });
        const json = JSON.parse(response.text);
        return json.suggestions || [];
    } catch (error) {
        console.error("Gemini action suggestion error:", error);
        throw new Error("Failed to get suggestions from Gemini API.");
    }
};

export const editImageWithMask = async (prompt: string, imageBase64: string, maskBase64?: string): Promise<{image: string, text: string}> => {
    const client = getGenAIClient();
    if (!client) throw new Error("Gemini client not initialized. API Key may be missing or invalid.");

    const modelName = 'gemini-2.5-flash-image-preview';

    const imagePart = { inlineData: { mimeType: 'image/jpeg', data: imageBase64 } };
    const textPart = { text: prompt };
    
    const parts = [imagePart, textPart];
    if (maskBase64) {
        const maskPart = { inlineData: { mimeType: 'image/png', data: maskBase64 }};
        parts.splice(1, 0, maskPart);
    }

    try {
        const response = await client.models.generateContent({
            model: modelName,
            contents: { parts },
            config: {
                responseModalities: [Modality.IMAGE, Modality.TEXT],
            },
        });

        let newImageBase64 = '';
        let newText = '';

        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                newImageBase64 = part.inlineData.data;
            } else if (part.text) {
                newText = part.text;
            }
        }
        
        if (!newImageBase64) {
            throw new Error("Image editing API did not return an image.");
        }

        return { image: newImageBase64, text: newText };
    } catch(e) {
        console.error("Gemini image editing error:", e);
        throw new Error("Failed to edit image with Gemini API.");
    }
};


export const generateOnboardingFromImage = async (imageBase64: string): Promise<{name: string, backstory: string, openingPrompt: string}> => {
    const client = getGenAIClient();
    if (!client) throw new Error("Gemini client not initialized. API Key may be missing or invalid.");
    
    const modelName = useStore.getState().settings.engine.cloud.textModel;

    const imagePart = { inlineData: { mimeType: 'image/jpeg', data: imageBase64 } };
    const textPart = { text: "Analyze this character portrait. Based on their appearance, invent a creative character name, a short, compelling backstory (2-3 sentences), and an exciting opening story prompt for a fantasy RPG." };
    
    try {
        const response = await client.models.generateContent({
            model: modelName,
            contents: { parts: [imagePart, textPart] },
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        name: { type: Type.STRING },
                        backstory: { type: Type.STRING },
                        openingPrompt: { type: Type.STRING }
                    }
                }
            }
        });

        return JSON.parse(response.text);

    } catch (e) {
        console.error("Gemini onboarding generation error:", e);
        throw new Error("Failed to generate character from image.");
    }
}